### ISSUE TITLE
Terrain Reference Feedback

### ISSUE THREAD

**Issue by StanzillaManticore** [ManticoreGamesInc/platform-documentation#271]
NO...I was hoping for more information on measurements concerning voxel distance and per pixel translation using a heightmap.

URL: https://docs.coregames.com/tutorials/terrain_reference/

**Comment by nicholasforeman** [comment]
To add on, many people in the Discord have been pretty confused because they were both having issues importing and/or generating, plus trying to transfer from 8bit in photoshop to 16bit. (Source: Search "heightmap").

Whoever made this feedback was probably trying to find information on heightmaps and Core is pretty lacking in my opinion.

**Comment by nicholasforeman** [comment]
Followup: the person asking is Harlequin01 (in Discord and Core).
