### ISSUE TITLE
Persistent Storage Feedback

### ISSUE THREAD

**Issue by StanzillaManticore** [ManticoreGamesInc/platform-documentation#316]
User: flodihn
Message: When in multiplayer, this example updates the score for all players. Not just the one clicking on the 1 button.

URL: https://docs.coregames.com/tutorials/persistent_storage/

**Comment by CommanderFoo** [comment]
This tutorial probably needs a complete rewrite (of the code and explanation) if the issue reported is to be addressed, as it will effect both parts of the tutorial.  

The problem is that considering it is a glimpse into persistent storage for beginners, it may get a little too confusing as contexts will likely need to be discussed along with script separation (server, client).  Part 1 of the tutorial relies on doing everything on the server (hence the issue with incorrect name and score displayed), and I understand the reason for this in the tutorial, and that is to make it easier for beginners to follow.

I would be willing to do a complete rewrite unless there are objections?

Edit:  I should clarify what I meant by "rewrite".  I didn't explain properly.  I meant the rewriting of the code and explanation parts.

I see this has been assigned now, so no worries.  Thought I would try and help out when I find some time :)

**Comment by StanzillaManticore** [comment]
Heya, we're currently working on a rewritten version of that, what were your plans for it? We can probably incorporate any feedback you might have.
